name: Run auto update
on:
  repository_dispatch:
  schedule:
    - cron: '0 8 * * *'
jobs:
  update_dependencies:
    if: (github.event_name == 'repository_dispatch' && github.event.action == 'update_dependencies') ||
      (github.event_name == 'schedule')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run auto update
        run: ./gradlew upgradeDependencies
        env:
          gitHubWriteToken: ${{ secrets.RELEASES_HUB_TOKEN }}